### ISSUE TITLE
Character 78,79,80 incorrect sprites during movements

### ISSUE THREAD

**Issue by ryanmcdonough** [loic-sharma/Pokemon#1]
If you select characters 78,79 or 80 - those at the bottom of the sprite png file - during movement the code will then select characters from the top row.

Correct image.
![correct](https://cloud.githubusercontent.com/assets/86820/4387030/a91f93ac-43d7-11e4-8fe2-95ee648909f3.PNG)

Then press left button twice and it takes character 1's sprite image.
![incorrect](https://cloud.githubusercontent.com/assets/86820/4387029/94016eaa-43d7-11e4-8c30-a0e97c516af2.PNG)

**Comment by loic-sharma** [comment]
Hey, thanks for reporting. I am no longer maintaining this project - this was just a toy project I did for fun over a weekend. Feel free to send a pull request though! :)
